spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nishanthkumarpathi/alphaprojectconfig.git
          clone-on-start: true
